export const funFacts = [
  "Le métro parisien a ouvert le 19 juillet 1900, à l'occasion de l'Exposition universelle.",
  "Le créateur du métro parisien est l'ingénieur breton Fulgence Bienvenüe.",
  "La ligne 1 a été creusée à ciel ouvert, éventrant la rue de Rivoli pendant des mois.",
  "Avant le métro, les Parisiens se déplaçaient en omnibus tirés par des chevaux.",
  "La ligne 14, ouverte en 1998, est la première ligne entièrement automatique du métro parisien.",
  "« Rue d'Allemagne » et « Berlin » sont devenues Jaurès et Liège en 1914, en pleine guerre.",
  "Châtelet-Les Halles est la plus grande gare souterraine du monde, avec 8 lignes.",
  "Le labyrinthe de Châtelet est volontaire : il évite les bousculades aux heures de pointe.",
  "La ligne 3 Bis, entre Gambetta et Porte des Lilas, ne fait que 1,3 km.",
  "La ligne 14 est la plus rapide ligne du réseau, avec près de 40 km/h de moyenne.",
  "La ligne 4, très sinueuse, est la ligne la plus lente du réseau.",
  "Aux heures de pointe, la ligne 7 fait circuler jusqu'à 60 trains par heure.",
  "Abbesses est la station la plus profonde du réseau, à 36 mètres sous terre.",
  "Sans ascenseur, il faut grimper 176 marches pour sortir d'Abbesses.",
  "La station Télégraphe, pourtant souterraine, est plus haute que certaines stations aériennes.",
  "Le métro transporte plus d'un milliard de voyageurs chaque année.",
  "Paris cache une dizaine de stations fantômes, jamais ouvertes ou fermées depuis longtemps.",
  "Sous le Parc des Princes se cache Porte Molitor, une station jamais ouverte au public.",
  "Place des Fêtes et Blanche ont été conçues comme abris antiaériens entre les deux guerres.",
  "Pendant la Seconde Guerre mondiale, des stations sont devenues des refuges pour les civils.",
  "Le carrelage blanc biseauté a été dessiné par Hector Guimard pour mieux réfléchir la lumière.",
  "La station Arts et Métiers a été transformée en 1994 façon sous-marin de Jules Verne.",
  "En 1909, Père Lachaise a inauguré le tout premier escalator du métro, en bois.",
  "Jusqu'en 1992, des wagons jaunes offraient une première classe plus confortable.",
  "Dans les années 90, la RATP a testé un parfum « Madeleine » pour masquer les odeurs.",
  "Les poinçonneurs d'antan étaient réputés pour leurs remarques bien senties envers les retardataires.",
  "Plus de 1300 objets sont perdus chaque jour dans le métro parisien.",
  "Serge le Lapin, mascotte prévention de la RATP, existe depuis 1977",
];
